// <auto-generated />
using BusinessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookReturnPenaltyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookReturnPenaltyApp.Models.Countries", b =>
                {
                    b.Property<int>("ContryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Money");

                    b.Property<double>("Penalty");

                    b.Property<string>("Weekends");

                    b.HasKey("ContryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BookReturnPenaltyApp.Models.Holidays", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CountryContryId");

                    b.Property<int>("DayOfYearFor2017");

                    b.Property<float>("HolidayLength");

                    b.Property<string>("HolidayName");

                    b.HasKey("HolidayId");

                    b.HasIndex("CountryContryId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("BookReturnPenaltyApp.Models.Holidays", b =>
                {
                    b.HasOne("BookReturnPenaltyApp.Models.Countries", "Country")
                        .WithMany()
                        .HasForeignKey("CountryContryId");
                });
#pragma warning restore 612, 618
        }
    }
}
